### ISSUE TITLE
password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by Devilpacks** [toncenter/ton-indexer#13]
![image](https://user-images.githubusercontent.com/29253277/200337508-19be40d4-b14b-4905-bda1-f0ff05d134b5.png)
![image](https://user-images.githubusercontent.com/29253277/200337591-6dbf71eb-271b-4f9a-9245-b65832477c9d.png)
postgres_password filled by 'password' row

**Comment by Devilpacks** [comment]
forward_scheduler service

**Comment by Devilpacks** [comment]
echo -n 'password' >> postgres_password

**Comment by zakirgl** [comment]
suggestion does not work @mangyr97
