### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by Oskal174** [toncenter/ton-indexer#41]
For last release: https://github.com/toncenter/ton-indexer/tree/v0.4.2

You have really outdated readme file with installation instructions. It sends to unexisting branch at side repository. 

> Clone repository: git clone --recursive --branch cpp-indexer https://github.com/kdimentionaltree/ton-indexer

And wrong information about configuration.

> Create .env file with command ./configure.sh

Please fix it.

**Comment by kdimentionaltree** [comment]
Hello, thank you for your issue. The README file was updated in #65. Please, feel free to reopen the issue if you find some new problems in the readme file.
