### ISSUE TITLE
suggestion does not work @mangyr97

### ISSUE THREAD

**Issue by zakirgl** [toncenter/ton-indexer#57]
suggestion does not work @mangyr97

_Originally posted by @zakirgl in https://github.com/toncenter/ton-indexer/issues/13#issuecomment-2122723924_

**Comment by Full-Hat** [comment]
User @mangyr97 told you to run following

**Comment by Full-Hat** [comment]
User @mangyr97 told you to run following
`echo -n 'password' >> postgres_password`
Did you run it in 'private' folder?
