### ISSUE TITLE
one PostgreSQL multiple index workers support

### ISSUE THREAD

**Issue by vataops** [toncenter/ton-indexer#72]
Is it okay for multiple index-workers to connect to a single PostgreSQL database? For example, I want to know if workers have a feature like Upsert

**Comment by dungeon-master-666** [comment]
Yes, currently all inserts have "ON CONFLICT" clause and it should work. However, you might face Postgres errors related to deadlocks since multiple clients insert the same data into it.

**Comment by vataops** [comment]
@dungeon-master-666 thank u!
